name: final_parola
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  beacons:
  scoped_model: 
  font_awesome_flutter:
  firebase_auth: 
  google_sign_in: 
  shared_preferences: 
  cloud_firestore: 
  firebase_core: 
  cached_network_image: 
    git: https://github.com/Cretezy/flutter_cached_network_image.git
  intl:
  battery:
  flutter_facebook_login:
  intro_views_flutter:
  firebase_storage:
  image_picker:
  flutter_scan_bluetooth:
  flutter_local_notifications:
  flutter_masked_text:
  splashscreen:
  fluro:
  flutter_offline:  
  flutter_spinkit:
  flutter_blue:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/bluetooth_icon.png
   - assets/battery_charge.png
   - assets/icons8-bluetooth-24.png
   - assets/icons8-empty-battery-50.png
   - assets/battery_charge.png
   - assets/lowbat.png
   - assets/lighthouse.png
   - assets/iconLighthouse.png
   - assets/lighthouse.gif
   - assets/lighthouse_app.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
